[package]
name = "azul-core"
version = "0.0.2"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Common datatypes used for the Azul document object model, shared across all azul-* crates
'''
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user-interface"]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
azul-css                = { path = "../azul-css",        version = "0.0.1"                  }
azul-css-parser         = { path = "../azul-css-parser", version = "0.0.1", optional = true }
gleam                   = { version = "0.11.0",                             optional = true }
lyon                    = { version = "0.15.8",  default-features = false,  optional = true }
usvg                    = { version = "0.10.0",  default-features = false,  optional = true }
rusttype                = { version = "0.9.2",   default-features = false,  features = ["std"], optional = true }
rayon                   = { version = "1.3.0",   default-features = false,  optional = true }

[features]
default = ["opengl"]
# Enables the CSS parser
css_parser = ["azul-css-parser"]
# Enables the OpenGL module (uses gleam)
opengl = ["gleam"]
# The SVG rendering module is pretty huge since it needs lyon - if you don't use
# SVG rendering in your app, you can turn this off to increase compilation
# speed and decrease your binary size
svg = ["lyon", "usvg", "rusttype", "rayon"]
