[package]
name = "azul-core"
version = "0.0.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Common datatypes used for the Azul document object model, shared across all azul-* crates
'''
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user-interface"]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
gleam                   = { version = "0.11.0" }
azul-css                = { version = "0.0.1" }
azul-css-parser         = { version = "0.0.1",  optional = true }

[features]
css_parser = ["azul-css-parser"]
