[package]
name = "azul-web"
version = "0.0.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = "Web API implementation for the Azul GUI toolkit"
documentation = "https://docs.rs/azul"
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user interface", "svg", "graphics" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
readme = "../README.md"
exclude = ["../assets/*", "../doc/*", "../examples/*"]
autoexamples = false
edition = "2018"

[dependencies]
azul-core = { version = "0.0.1", path = "../azul-core", default-features = false }
azul-css  = { version = "0.0.1", path = "../azul-css", default-features = false }