[package]
name = "azul-text-layout"
version = "0.0.4"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Text layout algorithms Azul desktop GUI framework
'''
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "native" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"
readme = "./README.md"

[dependencies]
azul-css                = { path = "../azul-css", version = "0.0.1",   default-features = false }
azul-core               = { path = "../azul-core", version = "0.0.2",   default-features = false }
unicode-normalization   = { version = "0.1.12",  default-features = false }
allsorts                = { version = "0.4.0", default-features = false }
