language: rust

sudo: false

cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

# We can't test OpenGL 3.2 on Travis, the shader compilation fails
# because glium does a check first if it has a OGL 3.2 context
script:
  - cargo build --verbose --examples
  - RUST_BACKTRACE=1 cargo test --verbose --features "doc-test no-opengl-tests"

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/azul-*;