language: rust
cache: cargo
sudo: required
rust:
  - 1.28.0

os:
  - linux
#  - osx

matrix:
  fast_finish: true

notifications:
  email: false

# We can't test OpenGL 3.2 on Travis, the shader compilation fails
# because glium does a check first if it has a OGL 3.2 context
script:
#  - cargo check --verbose --examples
#  - cargo check --no-default-features
#  - cargo check --no-default-features --features="svg"
#  - cargo check --no-default-features --features="image_loading"
#  - cargo check --no-default-features --features="logging"
  - RUST_BACKTRACE=1 cargo test --verbose --features "doc-test no-opengl-tests"

install:
  - PATH=$PATH:/home/travis/.cargo/bin

addons:
  apt:
    update: true
    packages:
      - libcurl4-openssl-dev      # for kcov
      - libelf-dev                # for kcov
      - libdw-dev                 # for kcov
      - cmake                     # for kcov
      - binutils-dev              # for kcov
      - libiberty-dev             # for kcov

after_success:
- |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&
  unzip master.zip && mv kcov-master kcov && mkdir kcov/build && cd kcov/build &&
  cmake .. && make && make install DESTDIR=../built && cd ../.. &&
  for file in ./target/debug/*; do ./kcov/built/usr/local/bin/kcov --verify --exclude-pattern=/.cargo,$PWD/target/debug/build,$PWD/tests ./target/kcov ${file}; done &&
  ./kcov/built/usr/local/bin/kcov --coveralls-id=${TRAVIS_JOB_ID} --merge ./target/kcov-merge ./target/kcov