language: rust
cache: cargo
rust:
  - 1.44.0

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
    - os: osx

notifications:
  email: false

# We can't test OpenGL 3.2 on Travis, the shader compilation fails
# because glium does a check first if it has a OGL 3.2 context
script:
  - python3 ./build.py

install:
  - PATH=$PATH:/home/travis/.cargo/bin

addons:
  apt:
    update: true
    packages:
      - libfreetype6-dev          # for webrender
      - libcurl4-openssl-dev      # for kcov
      - libelf-dev                # for kcov
      - libdw-dev                 # for kcov
      - cmake                     # for kcov
      - binutils-dev              # for kcov
      - libiberty-dev             # for kcov

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov $(find target/debug -maxdepth 1 -executable -name azul-\*)

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "azul.zip"
  skip_cleanup: true
  on:
    tags: true