[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
webrender = { git = "https://github.com/servo/webrender", rev = "00b85801f8c09431e5963a9e1dcd1a9087b744b9" }
cassowary = "0.3.0"
simplecss = "0.1.0"
twox-hash = "1.1.0"
glium = "0.20.0"
gleam = "0.4.20"
euclid = "0.17"
image = "0.18.0"
rusttype = "0.5.2"
app_units = "0.6"

[features]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
doc-test = []