[workspace]
members = [
    "api/rust",
    "azul-dll",
    "azul-desktop",
    "azulc",
    "azul-css",
    "azul-core",
    "azul-layout",
    "azul-text-layout",
    "azul-css-parser",
    "examples",
]

[profile.dev]
opt-level = 3
lto = "fat"
panic = "abort"
debug = true

[profile.release]
opt-level = 's'
lto = false
panic = "unwind"
codegen-units = 16
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false