[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
cassowary = "0.3.0"
simplecss = "0.1.0"
twox-hash = "1.1.0"
glium = "0.21.0"
gleam = "0.5"
euclid = "0.17"
image = "0.19.0"
rusttype = "0.5.2"
app_units = "0.6"
unicode-normalization = "0.1.5"
harfbuzz_rs = "0.1.0"
svg = "0.5.10"
lyon = { version = "0.10.0", features = ["extra"] }
lazy_static = "1.0.1"

[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "2e381e0325f367429810099d5abf76e674f697ed"

[features]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
doc-test = []

# Some test have to be disabled for Travis, since Travis does not
# use OpenGL 3.2, so the tests will fail
#
# To actually test the library, run cargo --test --features=doc-test
no-opengl-tests = []