[profile.dev]
opt-level = 3
lto = "fat"
panic = "abort"
debug = true

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
codegen-units = 1
debug = false
overflow-checks = false
# incremental = false

[workspace]
members = [
    "api/rust",
    "azul-dll",
    "azul-desktop",
    "azul-web",
    "azulc",
    "azul-css",
    "azul-core",
    "azul-layout",
    "azul-text-layout",
    "azul-widgets",
    "azul-css-parser",
    "examples",
]
