[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
webrender = { git = "https://github.com/servo/webrender", rev = "30cfecc343e407ce277d07cf09f27ad9dd1917a1" }
cassowary = "0.3.0"
simplecss = "0.1.0"
twox-hash = "1.1.0"
glium = "0.20.0"
gleam = "0.4.20"
euclid = "0.17"
