[workspace]
members = [
    "azul",
    "azul-dll",
    "azul-desktop",
    "azul-web",
    "azulc",
    "azul-css",
    "azul-core",
    "azul-layout",
    "azul-text-layout",
    "azul-widgets",
    "azul-css-parser",
    "azul-native-style",
]
