[package]
name = "azul-layout"
version = "0.0.3"
authors = ["Emil Sjölander <emil@visly.app>", "fschutt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Flexbox layout solver the Azul GUI framework
'''
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "css" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"

[dependencies]
azul-css            = { version = "0.0.1" }
azul-core           = { version = "0.0.2", default-features = false, features = ["opengl"] }
azul-text-layout    = { version = "0.0.2", optional = true }

[dev-dependencies]
azul-css-parser             = { version = "0.0.1"  }
azulc                       = { version = "0.0.1"  }

[features]
default = []
text_layout = ["azul-text-layout"]

[[example]]
name = "layout_tests"
path = "../../examples/layout_tests/layout_tests.rs"
required-features = []