[package]
name = "azul-layout"
version = "0.0.1"
authors = ["Emil Sjölander <emil@visly.app>", "fschutt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Flexbox layout solver the Azul GUI framework
'''
documentation = "https://docs.rs/azul"
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "css" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"

[dependencies]
azul-core           = { version = "0.0.1" }
azul-css            = { version = "0.0.1" }
azul-text-layout    = { version = "0.0.1", optional = true }

# [dev-dependencies]
# azul-css-parser             = { version = "0.0.1", path = "../azul-css-parser"  }
# azulc                       = { version = "0.0.1", path = "../azulc"  }

[features]
default = []
text_layout = ["azul-text-layout"]

[[example]]
name = "layout_tests"
path = "../../examples/layout_tests/layout_tests.rs"
required-features = []