[package]
name = "azulc"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Azul XML-to-Rust compiler (and library)
'''
documentation = "https://docs.rs/azulc"
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user interface"]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
readme = "README.md"
exclude = ["assets/*", "doc/*", "examples/*"]
autoexamples = false
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]
path = "../../azulc/lib.rs"
default-features = []

[[bin]]
name = "azulc"
path = "../../azulc/main.rs"
default-features = ["text_layout"]

[dependencies]
gleam                   = { version = "0.6",            default-features = false                                        }
xmlparser               = { version = "0.9.0",          default-features = false                                        }
azul-core               = { version = "0.1.0",          default-features = false,       path = "../azul-core"           }
azul-css                = { version = "0.1.0",          default-features = false,       path = "../azul-css"            }
azul-css-parser         = { version = "0.1.0",          default-features = false,       path = "../azul-css-parser"     }
azul-layout             = { version = "0.1.0",          default-features = false,       path = "../azul-layout"         }

[features]
text_layout = ["azul-layout/text_layout"]
