[package]
name = "azul-dll"
version = "0.0.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = "C-API of Azul GUI"
documentation = "https://docs.rs/azul"
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "css" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"

[dependencies]
azul-core = { version = "0.0.1", path = "../azul-core", default-features = false }
azul-css  = { version = "0.0.1", path = "../azul-css", default-features = false }
azul-native-style = { version = "0.0.1", path = "../azul-native-style", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
azul-desktop = { version = "0.0.1", path = "../azul-desktop", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
azul-web = { version = "0.0.1", path = "../azul-web", default-features = false }

