[package]
name = "azul-dll"
version = "0.0.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = "C-API of Azul GUI"
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "css" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2018"
build = "build.rs"
autoexamples = false

[[bin]]
name = "azul-dll"
path = "main.rs"
edition = "2018"

[lib]
name = "azul"
edition = "2018"
crate-type = ["cdylib", "staticlib", "rlib"]
doc = false

[profile.dev]
opt-level = 1
lto = false
panic = "unwind"
debug = false

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
codegen-units = 1
debug = false
overflow-checks = false
incremental = false

[dependencies]
azul-core = { path = "../azul-core", version = "0.0.2", default-features = false, features = ["opengl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
azul-desktop = { path = "../azul-desktop", version = "0.0.5", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
azul-web = { path = "../azul-web", version = "0.0.5", default-features = false }

[build-dependencies]
tar = "0.4"
flate2 = "1.0.14"

[features]
default = ["logging", "css_parser", "image_loading", "font_loading", "text_layout", "svg", "std"]
# Enable standard library (on by default)
std = ["azul-core/std", "azul-desktop/std", "azul-core/multithreading"]
# Enable logging & error reporting
logging = ["azul-desktop/logging"]
# Enable / diable the CSS parser
css_parser = ["azul-desktop/css_parser"]
# Enables loading images - if you don't need to use images in your app, disable this for faster compilation speed
image_loading = ["azul-desktop/image_loading"]
# Enables loading of ICO files on the image decoder
ico = ["azul-desktop/ico"]
# Enables loading of TGA files on the image decoder
tga = ["azul-desktop/tga"]
# Enables loading of HDR files on the image decoder
hdr = ["azul-desktop/hdr"]
# Enables parallel JPEG decoding on the image decoder
jpeg_rayon = ["azul-desktop/jpeg_rayon"]
# Enables loading of DXT files on the image decoder
dxt = ["azul-desktop/dxt"]
# Enables loading of WEBP files on the image decoder
webp = ["azul-desktop/webp"]
# Enables loading of PNM files on the image decoder
pnm = ["azul-desktop/pnm"]
# Activates the font-loading module, important to deactivate for example
font_loading = ["azul-desktop/font_loading"]
# Text loading module, disable if you have a custom text layouting function
text_layout = ["azul-desktop/text_layout"]
# Whether to include SVG processing (adds dependencies for lyon, usvg and xmlparser)
svg = ["azul-desktop/svg"]