name: Rust

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          
      - name: Install dependencies
        run: sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Check (Linux)
        run: cd azul-dll && cargo check
        
      - name: Build
        run: cd azul-dll && cargo build --verbose --release
    
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Check (Windows)
        run: cd azul-dll && cargo check
        
      - name: Build (Windows)
        run: cd azul-dll && cargo build --verbose --release
             
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Check (Mac)
        run: cd azul-dll && cargo check

      - name: Build (Mac)
        run: cd azul-dll && cargo build --verbose --release
