name: Rust

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          
      - name: Install dependencies
        run: sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build
        run: cd azul-dll && cargo build --verbose --release
      
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cd azul-dll && cargo build --verbose --release
      
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cd azul-dll && cargo build --verbose --release
      
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
